use serde::{Deserialize, Serialize};

use crate::Error;

/// Trait generated by `#[derive(BromEntity)]` for each content struct.
/// Provides compile-time metadata about the entity's schema.
///
/// # Safety
///
/// Implementations must ensure that `table_name()` and the `name` field of all `FieldInfo`
/// returned by `fields()` are compile-time constants (e.g., string literals).
/// This is a critical security invariant because the repository layer uses these
/// values to construct dynamic SQL queries. Providing runtime user input here
/// would introduce risk of SQL injection.
pub trait EntitySchema: Sized + Send + Sync + 'static {
    /// `SQLite` table name for this entity.
    fn table_name() -> &'static str;
    /// Ordered list of field metadata.
    fn fields() -> Vec<FieldInfo>;
    /// Complete schema information including auth policy.
    fn schema_info() -> SchemaInfo;
}

/// Metadata for a single field of an entity.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct FieldInfo {
    /// The programmatic name of the field.
    pub name: String,
    /// The storage and logic type of the field.
    pub field_type: FieldType,
    /// Constraints applied to this field (e.g., `NotNull`).
    pub constraints: Vec<Constraint>,
    /// Optional UI widget identifier for rendering.
    pub ui_widget: Option<String>,
    /// Whether the field is hidden from the public UI.
    pub hidden: bool,
}

/// High-level data types supported by the `brom` entity system.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum FieldType {
    /// A UTF-8 string.
    String,
    /// A 64-bit signed integer.
    Integer,
    /// A double-precision floating point number.
    Float,
    /// A boolean value.
    Boolean,
    /// A timestamp.
    DateTime,
    /// A 1:N relationship to another entity.
    Link {
        /// The target entity table name.
        target: String,
    },
    /// An M:N relationship to another entity.
    ManyToMany {
        /// The target entity table name.
        target: String,
        /// The automatically generated junction table name.
        junction_table: String,
    },
}

/// Schema-level constraints for database fields.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum Constraint {
    /// Field must be unique across all records.
    Unique,
    /// Field cannot be null.
    NotNull,
    /// Default value for the field.
    Default(String),
}

/// Complete schema information including auth policy.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SchemaInfo {
    /// The database table name.
    pub table_name: String,
    /// Metadata for all fields in the entity.
    pub fields: Vec<FieldInfo>,
    /// The security policy governing access.
    pub auth_policy: AuthPolicy,
}

/// Security policy governing endpoint and database access.
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
pub enum AuthPolicy {
    /// No authentication required.
    #[default]
    Public,
    /// Valid API key required for bearer authentication.
    ApiKey,
    /// Admin login session required.
    AdminOnly,
}

/// High-level pagination metadata for list responses.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Pagination {
    /// Current page number (1-indexed).
    pub page: u64,
    /// Number of items per page.
    pub per_page: u64,
}

impl Default for Pagination {
    fn default() -> Self {
        Self {
            page: 1,
            per_page: 25,
        }
    }
}

/// Generic CRUD interface for entity persistence.
#[cfg_attr(feature = "testing", mockall::automock)]
pub trait Repository<T: EntitySchema + Serialize + serde::de::DeserializeOwned>:
    Send + Sync
{
    /// Creates a new entity in the repository.
    ///
    /// # Errors
    /// Returns `Error::SchemaError` or other internal errors on failure.
    fn create(&self, entity: &T) -> Result<i64, Error>;

    /// Finds an entity by its ID.
    ///
    /// # Errors
    /// Returns `Error::SchemaError` or other internal errors on failure.
    fn find_by_id(&self, id: i64) -> Result<Option<T>, Error>;

    /// Finds all entities matching the given pagination.
    ///
    /// # Errors
    /// Returns `Error::SchemaError` or other internal errors on failure.
    fn find_all(&self, pagination: &Pagination) -> Result<Vec<T>, Error>;

    /// Updates the entity with the given ID.
    ///
    /// # Errors
    /// Returns `Error::SchemaError` or other internal errors on failure.
    fn update(&self, id: i64, entity: &T) -> Result<(), Error>;

    /// Deletes the entity with the given ID.
    ///
    /// # Errors
    /// Returns `Error::SchemaError` or other internal errors on failure.
    fn delete(&self, id: i64) -> Result<(), Error>;

    /// Returns the total count of entities.
    ///
    /// # Errors
    /// Returns `Error::SchemaError` or other internal errors on failure.
    fn count(&self) -> Result<i64, Error>;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[allow(clippy::unwrap_used)]
    fn field_type_serde_roundtrip() {
        let ft = FieldType::String;
        let json = serde_json::to_string(&ft).unwrap();
        let parsed: FieldType = serde_json::from_str(&json).unwrap();
        assert_eq!(ft, parsed);
    }

    #[test]
    #[allow(clippy::unwrap_used)]
    fn field_type_link_serde_roundtrip() {
        let ft = FieldType::Link {
            target: "category".into(),
        };
        let json = serde_json::to_string(&ft).unwrap();
        let parsed: FieldType = serde_json::from_str(&json).unwrap();
        assert_eq!(ft, parsed);
    }

    #[test]
    #[allow(clippy::unwrap_used)]
    fn field_type_many_to_many_serde_roundtrip() {
        let ft = FieldType::ManyToMany {
            target: "tag".into(),
            junction_table: "post_tag".into(),
        };
        let json = serde_json::to_string(&ft).unwrap();
        let parsed: FieldType = serde_json::from_str(&json).unwrap();
        assert_eq!(ft, parsed);
    }

    #[test]
    #[allow(clippy::unwrap_used)]
    fn constraint_serde_roundtrip() {
        let c = Constraint::NotNull;
        let json = serde_json::to_string(&c).unwrap();
        let parsed: Constraint = serde_json::from_str(&json).unwrap();
        assert_eq!(c, parsed);
    }

    #[test]
    fn auth_policy_defaults_to_public() {
        assert_eq!(AuthPolicy::default(), AuthPolicy::Public);
    }

    #[test]
    fn pagination_defaults() {
        let p = Pagination::default();
        assert_eq!(p.page, 1);
        assert_eq!(p.per_page, 25);
    }
}
