use serde::{Deserialize, Serialize};

use crate::Error;

/// Trait generated by `#[derive(BromEntity)]` for each content struct.
/// Provides compile-time metadata about the entity's schema.
///
/// # Safety
///
/// Implementations must ensure that `table_name()` returns a compile-time constant
/// (the return type `&'static str` enforces this). The `name` field of `FieldInfo`
/// returned by `fields()` should also be a compile-time constant, though this is
/// not structurally enforced by the type system (it uses `String` for serde
/// compatibility). As a defense-in-depth measure, the persistence layer validates
/// all identifier values at runtime via [`validate_sql_identifier`] before SQL
/// interpolation.
pub trait EntitySchema: Sized + Send + Sync + 'static {
    /// `SQLite` table name for this entity.
    fn table_name() -> &'static str;
    /// Ordered list of field metadata.
    fn fields() -> Vec<FieldInfo>;
    /// Complete schema information including auth policy.
    fn schema_info() -> SchemaInfo;
}

/// Metadata for a single field of an entity.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct FieldInfo {
    /// The programmatic name of the field.
    pub name: String,
    /// The storage and logic type of the field.
    pub field_type: FieldType,
    /// Constraints applied to this field (e.g., `NotNull`).
    pub constraints: Vec<Constraint>,
    /// Optional UI widget identifier for rendering.
    pub ui_widget: Option<String>,
    /// Whether the field is hidden from the public UI.
    pub hidden: bool,
}

/// High-level data types supported by the `brom` entity system.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum FieldType {
    /// A UTF-8 string.
    String,
    /// A 64-bit signed integer.
    Integer,
    /// A double-precision floating point number.
    Float,
    /// A boolean value.
    Boolean,
    /// A timestamp.
    DateTime,
    /// A 1:N relationship to another entity.
    Link {
        /// The target entity table name.
        target: String,
    },
    /// An M:N relationship to another entity.
    ManyToMany {
        /// The target entity table name.
        target: String,
        /// The automatically generated junction table name.
        junction_table: String,
    },
}

/// Schema-level constraints for database fields.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum Constraint {
    /// Field must be unique across all records.
    Unique,
    /// Field cannot be null.
    NotNull,
    /// Default value for the field.
    Default(String),
}

/// Validates that a string is a safe SQL identifier.
///
/// A valid identifier contains only ASCII alphanumeric characters and underscores,
/// starts with a letter or underscore, and is between 1 and 128 characters.
///
/// # Errors
///
/// Returns [`Error::SchemaError`] if the identifier contains invalid characters,
/// is empty, or exceeds 128 characters.
///
/// # Panics
///
/// This function does not panic. The internal use of `expect` is guarded by an
/// earlier non-empty check.
pub fn validate_sql_identifier(s: &str) -> Result<&str, Error> {
    // Defense-in-depth: reject critical SQLite reserved words.
    const RESERVED: &[&str] = &[
        "select",
        "insert",
        "update",
        "delete",
        "drop",
        "create",
        "alter",
        "table",
        "index",
        "from",
        "where",
        "values",
        "set",
        "into",
        "order",
        "group",
        "having",
        "limit",
        "join",
        "on",
        "as",
        "and",
        "or",
        "not",
        "null",
        "primary",
        "foreign",
        "key",
        "references",
        "constraint",
        "default",
        "check",
        "unique",
        "column",
        "add",
    ];

    if s.is_empty() || s.len() > 128 {
        return Err(Error::SchemaError(format!(
            "SQL identifier must be 1-128 characters, got {len}",
            len = s.len()
        )));
    }
    let mut chars = s.chars();
    // Safety: Guarded by s.is_empty() check above.
    #[allow(clippy::expect_used)]
    let first = chars.next().expect("checked non-empty above");
    if !first.is_ascii_alphabetic() && first != '_' {
        return Err(Error::SchemaError(format!(
            "SQL identifier must start with a letter or underscore, got '{first}'"
        )));
    }
    if let Some(bad) = chars.find(|c| !c.is_ascii_alphanumeric() && *c != '_') {
        return Err(Error::SchemaError(format!(
            "SQL identifier contains invalid character '{bad}' in '{s}'"
        )));
    }

    let lower = s.to_ascii_lowercase();
    if RESERVED.iter().any(|r| *r == lower) {
        return Err(Error::SchemaError(format!(
            "SQL identifier '{s}' is a reserved word"
        )));
    }

    Ok(s)
}

/// Complete schema information including auth policy.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SchemaInfo {
    /// The database table name.
    pub table_name: String,
    /// Metadata for all fields in the entity.
    pub fields: Vec<FieldInfo>,
    /// The security policy governing access.
    pub auth_policy: AuthPolicy,
}

/// Security policy governing endpoint and database access.
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
pub enum AuthPolicy {
    /// No authentication required.
    #[default]
    Public,
    /// Valid API key required for bearer authentication.
    ApiKey,
    /// Admin login session required.
    AdminOnly,
}

/// High-level pagination metadata for list responses.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Pagination {
    /// Current page number (1-indexed).
    pub page: u64,
    /// Number of items per page.
    pub per_page: u64,
}

impl Pagination {
    /// Maximum number of items allowed per page to prevent `DoS`.
    pub const MAX_PER_PAGE: u64 = 100;

    /// Creates a new pagination request with boundary enforcement.
    ///
    /// - `page` is saturated to at least 1.
    /// - `per_page` is saturated to at least 1 and capped at `Self::MAX_PER_PAGE`.
    pub fn new(page: u64, per_page: u64) -> Self {
        Self {
            page: page.max(1),
            per_page: per_page.clamp(1, Self::MAX_PER_PAGE),
        }
    }
}

impl Default for Pagination {
    fn default() -> Self {
        Self {
            page: 1,
            per_page: 25,
        }
    }
}

/// Generic CRUD interface for entity persistence.
#[cfg_attr(feature = "testing", mockall::automock)]
pub trait Repository<T: EntitySchema + Serialize + serde::de::DeserializeOwned>:
    Send + Sync
{
    /// Creates a new entity in the repository.
    ///
    /// # Errors
    /// Returns `Error::SchemaError` or other internal errors on failure.
    fn create(&self, entity: &T) -> Result<i64, Error>;

    /// Finds an entity by its ID.
    ///
    /// # Errors
    /// Returns `Error::SchemaError` or other internal errors on failure.
    fn find_by_id(&self, id: i64) -> Result<Option<T>, Error>;

    /// Finds all entities matching the given pagination.
    ///
    /// # Errors
    /// Returns `Error::SchemaError` or other internal errors on failure.
    fn find_all(&self, pagination: &Pagination) -> Result<Vec<T>, Error>;

    /// Updates the entity with the given ID.
    ///
    /// # Errors
    /// Returns `Error::SchemaError` or other internal errors on failure.
    fn update(&self, id: i64, entity: &T) -> Result<(), Error>;

    /// Deletes the entity with the given ID.
    ///
    /// # Errors
    /// Returns `Error::SchemaError` or other internal errors on failure.
    fn delete(&self, id: i64) -> Result<(), Error>;

    /// Returns the total count of entities.
    ///
    /// # Errors
    /// Returns `Error::SchemaError` or other internal errors on failure.
    fn count(&self) -> Result<i64, Error>;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[allow(clippy::unwrap_used)]
    fn field_type_serde_roundtrip() {
        let ft = FieldType::String;
        let json = serde_json::to_string(&ft).unwrap();
        let parsed: FieldType = serde_json::from_str(&json).unwrap();
        assert_eq!(ft, parsed);
    }

    #[test]
    #[allow(clippy::unwrap_used)]
    fn field_type_link_serde_roundtrip() {
        let ft = FieldType::Link {
            target: "category".into(),
        };
        let json = serde_json::to_string(&ft).unwrap();
        let parsed: FieldType = serde_json::from_str(&json).unwrap();
        assert_eq!(ft, parsed);
    }

    #[test]
    #[allow(clippy::unwrap_used)]
    fn field_type_many_to_many_serde_roundtrip() {
        let ft = FieldType::ManyToMany {
            target: "tag".into(),
            junction_table: "post_tag".into(),
        };
        let json = serde_json::to_string(&ft).unwrap();
        let parsed: FieldType = serde_json::from_str(&json).unwrap();
        assert_eq!(ft, parsed);
    }

    #[test]
    #[allow(clippy::unwrap_used)]
    fn constraint_serde_roundtrip() {
        let c = Constraint::NotNull;
        let json = serde_json::to_string(&c).unwrap();
        let parsed: Constraint = serde_json::from_str(&json).unwrap();
        assert_eq!(c, parsed);
    }

    #[test]
    fn auth_policy_defaults_to_public() {
        assert_eq!(AuthPolicy::default(), AuthPolicy::Public);
    }

    #[test]
    fn pagination_defaults() {
        let p = Pagination::default();
        assert_eq!(p.page, 1);
        assert_eq!(p.per_page, 25);
    }

    #[test]
    fn pagination_new_enforces_boundaries() {
        // Minimums
        let p = Pagination::new(0, 0);
        assert_eq!(p.page, 1);
        assert_eq!(p.per_page, 1);

        // Maximums
        let p = Pagination::new(10, 1000);
        assert_eq!(p.page, 10);
        assert_eq!(p.per_page, Pagination::MAX_PER_PAGE);

        // Valid range
        let p = Pagination::new(5, 50);
        assert_eq!(p.page, 5);
        assert_eq!(p.per_page, 50);
    }

    #[test]
    fn validate_sql_identifier_accepts_valid() {
        assert!(validate_sql_identifier("user_name").is_ok());
        assert!(validate_sql_identifier("_private").is_ok());
        assert!(validate_sql_identifier("Col123").is_ok());
    }

    #[test]
    fn validate_sql_identifier_rejects_invalid() {
        assert!(validate_sql_identifier("").is_err());
        assert!(validate_sql_identifier("123abc").is_err());
        assert!(validate_sql_identifier("drop;--").is_err());
        assert!(validate_sql_identifier("Robert'); DROP TABLE students;--").is_err());
        assert!(validate_sql_identifier(&"a".repeat(129)).is_err());
    }

    #[test]
    fn validate_sql_identifier_rejects_reserved_words() {
        let reserved = [
            "select", "SELECT", "drop", "DROP", "table", "TABLE", "insert", "INSERT", "delete",
            "DELETE", "update", "UPDATE", "from", "FROM", "where", "WHERE", "create", "CREATE",
            "alter", "ALTER", "index", "INDEX",
        ];
        for word in reserved {
            assert!(
                validate_sql_identifier(word).is_err(),
                "expected '{word}' to be rejected as a reserved word"
            );
        }
    }
}
