use serde::{Deserialize, Serialize};

use crate::Error;

/// Trait generated by `#[derive(BromEntity)]` for each content struct.
/// Provides compile-time metadata about the entity's schema.
///
/// # Safety
///
/// Implementations must ensure that `table_name()` and the `name` field of all `FieldInfo`
/// returned by `fields()` are compile-time constants (e.g., string literals).
/// This is a critical security invariant because the repository layer uses these
/// values to construct dynamic SQL queries. Providing runtime user input here
/// would introduce risk of SQL injection.
pub trait EntitySchema: Sized + Send + Sync + 'static {
    /// `SQLite` table name for this entity.
    fn table_name() -> &'static str;
    /// Ordered list of field metadata.
    fn fields() -> Vec<FieldInfo>;
    /// Complete schema information including auth policy.
    fn schema_info() -> SchemaInfo;
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FieldInfo {
    pub name: String,
    pub field_type: FieldType,
    pub constraints: Vec<Constraint>,
    pub ui_widget: Option<String>,
    pub hidden: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum FieldType {
    String,
    Integer,
    Float,
    Boolean,
    DateTime,
    Link {
        target: String,
    },
    ManyToMany {
        target: String,
        junction_table: String,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum Constraint {
    Unique,
    NotNull,
    Default(String),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SchemaInfo {
    pub table_name: String,
    pub fields: Vec<FieldInfo>,
    pub auth_policy: AuthPolicy,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
pub enum AuthPolicy {
    #[default]
    Public,
    ApiKey,
    AdminOnly,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Pagination {
    pub page: u64,
    pub per_page: u64,
}

impl Default for Pagination {
    fn default() -> Self {
        Self {
            page: 1,
            per_page: 25,
        }
    }
}

/// Generic CRUD interface for entity persistence.
#[cfg_attr(feature = "testing", mockall::automock)]
pub trait Repository<T: EntitySchema + Serialize + serde::de::DeserializeOwned>:
    Send + Sync
{
    /// Creates a new entity in the repository.
    ///
    /// # Errors
    /// Returns `Error::SchemaError` or other internal errors on failure.
    fn create(&self, entity: &T) -> Result<i64, Error>;

    /// Finds an entity by its ID.
    ///
    /// # Errors
    /// Returns `Error::SchemaError` or other internal errors on failure.
    fn find_by_id(&self, id: i64) -> Result<Option<T>, Error>;

    /// Finds all entities matching the given pagination.
    ///
    /// # Errors
    /// Returns `Error::SchemaError` or other internal errors on failure.
    fn find_all(&self, pagination: &Pagination) -> Result<Vec<T>, Error>;

    /// Updates the entity with the given ID.
    ///
    /// # Errors
    /// Returns `Error::SchemaError` or other internal errors on failure.
    fn update(&self, id: i64, entity: &T) -> Result<(), Error>;

    /// Deletes the entity with the given ID.
    ///
    /// # Errors
    /// Returns `Error::SchemaError` or other internal errors on failure.
    fn delete(&self, id: i64) -> Result<(), Error>;

    /// Returns the total count of entities.
    ///
    /// # Errors
    /// Returns `Error::SchemaError` or other internal errors on failure.
    fn count(&self) -> Result<i64, Error>;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[allow(clippy::unwrap_used)]
    fn field_type_serde_roundtrip() {
        let ft = FieldType::String;
        let json = serde_json::to_string(&ft).unwrap();
        let parsed: FieldType = serde_json::from_str(&json).unwrap();
        assert_eq!(ft, parsed);
    }

    #[test]
    #[allow(clippy::unwrap_used)]
    fn field_type_link_serde_roundtrip() {
        let ft = FieldType::Link {
            target: "category".into(),
        };
        let json = serde_json::to_string(&ft).unwrap();
        let parsed: FieldType = serde_json::from_str(&json).unwrap();
        assert_eq!(ft, parsed);
    }

    #[test]
    #[allow(clippy::unwrap_used)]
    fn field_type_many_to_many_serde_roundtrip() {
        let ft = FieldType::ManyToMany {
            target: "tag".into(),
            junction_table: "post_tag".into(),
        };
        let json = serde_json::to_string(&ft).unwrap();
        let parsed: FieldType = serde_json::from_str(&json).unwrap();
        assert_eq!(ft, parsed);
    }

    #[test]
    #[allow(clippy::unwrap_used)]
    fn constraint_serde_roundtrip() {
        let c = Constraint::NotNull;
        let json = serde_json::to_string(&c).unwrap();
        let parsed: Constraint = serde_json::from_str(&json).unwrap();
        assert_eq!(c, parsed);
    }

    #[test]
    fn auth_policy_defaults_to_public() {
        assert_eq!(AuthPolicy::default(), AuthPolicy::Public);
    }

    #[test]
    fn pagination_defaults() {
        let p = Pagination::default();
        assert_eq!(p.page, 1);
        assert_eq!(p.per_page, 25);
    }
}
